# Generated by Django 4.2.30 on 2026-07-14 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_remove_article_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='שם הספר')),
                ('author', models.CharField(max_length=100, verbose_name='מחבר')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת (למשל: סימן א)')),
                ('order', models.PositiveIntegerField(verbose_name='סדר')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='articles.book', verbose_name='ספר')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hebrew_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='תאריך עברי'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='תוכן המאמר'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך יצירה'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='מפורסם'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='כותרת המאמר'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת הסעיף')),
                ('content', models.TextField(verbose_name='תוכן')),
                ('order', models.PositiveIntegerField(verbose_name='סדר')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='articles.chapter', verbose_name='פרק')),
            ],
        ),
    ]