# Generated by Django 4.2.30 on 2026-07-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0012_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hebrew_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='תאריך עברי'),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('path', models.CharField(max_length=500, verbose_name='נתיב שביקר בו')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='זמן ביקור')),
                ('user_agent', models.TextField(blank=True, verbose_name='דפדפן / מכשיר')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'לוג ביקור',
                'verbose_name_plural': 'לוגים של מבקרים',
                'ordering': ['-timestamp'],
            },
        ),
    ]
