# Generated by Django 4.2.30 on 2026-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_hebrew_date_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acronym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(db_index=True, max_length=100, verbose_name='ראשי תיבות')),
                ('meaning', models.TextField(verbose_name='פירוש / פיתוח ראשי תיבות')),
            ],
            options={
                'verbose_name': 'ראשי תיבות',
                'verbose_name_plural': 'מילון ראשי תיבות',
                'ordering': ['short'],
            },
        ),
    ]
