# Generated by Django 4.2.30 on 2026-08-02 08:56

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך הוספה'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='תוכן המאמר'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='תקציר הספר'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='תוכן'),
        ),
    ]
