# Generated by Django 4.2.30 on 2026-08-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_book_created_at_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorahText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100, verbose_name='ספר')),
                ('chapter', models.CharField(max_length=10, verbose_name='פרק')),
                ('verse', models.CharField(max_length=10, verbose_name='פסוק')),
                ('text_with_nikkud', models.TextField(verbose_name='טקסט מנוקד')),
                ('clean_text', models.TextField(blank=True, verbose_name='טקסט נקי (ללא ניקוד ורווחים)')),
            ],
            options={
                'verbose_name': 'טקסט תורני',
                'verbose_name_plural': 'טקסטים תורניים',
                'indexes': [models.Index(fields=['clean_text'], name='articles_to_clean_t_0b825d_idx')],
            },
        ),
    ]
