# Generated by Django 4.2.30 on 2026-09-15 17:26

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_torahtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorahTextFTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField(verbose_name='ספר')),
                ('chapter', models.TextField(verbose_name='פרק')),
                ('verse', models.TextField(verbose_name='פסוק')),
                ('text_with_nikkud', models.TextField(verbose_name='טקסט מנוקד')),
            ],
            options={
                'db_table': 'articles_torahtext_fts',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='word_imports/', verbose_name='ייבוא אוטומטי מוורד (מומלץ למאמרים עם הערות!)'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/', verbose_name='קובץ PDF להורדה'),
        ),
        migrations.AddField(
            model_name='section',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='word_imports/', verbose_name='ייבוא אוטומטי מוורד (מומלץ למאמרים עם הערות!)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='תוכן המאמר'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='תוכן'),
        ),
    ]
