# Generated by Django 4.2.30 on 2026-09-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_torahtextfts_article_word_file_book_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='קישור (Slug)'),
        ),
    ]
